### ISSUE TITLE
Pro icons (@hugeicons/react) don't tree-shake and increase bundle size by a lot

### ISSUE THREAD

**Issue by alea-git** [hugeicons/hugeicons#17]
Hi!

I've recently purchased the Pro version of hugeicons (@hugeicons/react) and using it in a NextJS app. And I've noticed a huge increase in bundle size because of it.

In particular our minified+gzipped bundle went from **400kb** to **600kb**, basically a 50% increase just because of the icons we use.

So I went through the rabbit hole, and apparently it's because every icon included in the app comes with all variants, automatically.

Ex: I want to use `ArrowRight01Icon`, hugeicons includes all `stroke`, `solid`, `twotone`, `bulk` variants, even though they're never used.

Can you do anything about it? This is a deal breaker for us (and I'm sure a lot of other projects).

**Comment by hugeicons** [comment]
Hi. 

We are working on this, and will fix it very soon.

**Comment by alea-git** [comment]
Such a good news to hear! Any ETA?

**Comment by hugeicons** [comment]
@alea-git We have published @hugeicons/react@0.8.0-beta.2 that supports tree-shaking for icons and variants, you can check it and let us know if you face any issues. 

You can now import icons that include all variant as: 
Home01Icon 

Or you can import single variant like:
  Home01IconBulkRounded
  Home01IconDuotoneRounded
  Home01IconSolidRounded
  Home01IconSolidSharp
  Home01IconSolidStandard
  Home01IconStrokeRounded
  Home01IconStrokeSharp
  Home01IconStrokeStandard
  Home01IconTwotoneRounded

**Comment by alea-git** [comment]
Thanks for the **very quick** update! 

I've updated the project to import just the variants we use but the tree shaking is still not taking place. 
When inspecting the production bundle I can still see:

```javascript
s("ThumbsUpIcon", {
    "bulk.rounded": hZ,
    "duotone.rounded": hW,
    "solid.rounded": hT,
    "solid.sharp": hE,
    "solid.standard": hA,
    "stroke.rounded": hD,
    "stroke.sharp": hO,
    "stroke.standard": hP,
    "twotone.rounded": hz
}),
```

And the bundle size didn't change at all.

I import icons like:

```typescript
export const AppIconsPlatformHomeLine = Home04IconStrokeRounded;
export const AppIconsPlatformSEOLine = SourceCodeIconStrokeRounded;
// etc...
```

Am I missing something?

---

Some stats about the project: it uses (totally) about 160 icons. 
The total bundle size added by these icons (with all variants) is 1.6MB (flatten, no gzip no minification).

Which is a loooot of javascript to parse initially, specially on mobile devices. 
That's why it's such an important update for us.

**Comment by hugeicons** [comment]
Hi alea-git,

Join us on Discord for dedicated support and assistance from our team.


https://discord.com/invite/mauDATBZgE

**Comment by aigahon** [comment]
@alea-git having the same issue, still not fixed. on top of it, version 1.0.0 doesn't even seem to be working at all..

**Comment by Forsect** [comment]
Not working and closed, classic xD
